### ISSUE TITLE
Очень круто получилось

### ISSUE THREAD

**Issue by twepl** [jdtcn/HybridBlazor#1]
Я бы рекомендовал написать целую библиотеку что бы ускорить сайты на blazor в момент первой загрузки.

**Comment by jdtcn** [comment]
Спасибо за отзыв.

Да, была такая идея, но в библотеке я особого смысла не вижу: всё равно _Hosts.cshtml вручную править, а приложение надо сразу писать с прицелом на работу в двух режимах. Думаю, рано или поздно эта возможность появится в самом фреймворке.
