### ISSUE TITLE
.NET 6 Preview - Issues Installing

### ISSUE THREAD

**Issue by wcrowther** [jdtcn/HybridBlazor#3]
I was not able to get your code running. Not sure what the issues were and I started with installing .NET Preview 6 tried to make it work from there. Not sure if there was some version mismatch or something.

Is the project dependent on the .NET 6 Preview? Or is there a way rollback the project files to work on .NET 5?

**Comment by jdtcn** [comment]
Hi, yes, this project uses NET 6 Preview 1, there should be SDK installed. Have you received any error messages? Could you please share them with me?

Theoretically, you can run this code on NET 5, for this you should downgrade the dependencies in the * .csproj files.

**Comment by wcrowther** [comment]
Here is what I am seeing. The 6.0 version I am using is 6.0.100-preview.1.21103.13

![image](https://user-images.githubusercontent.com/6372711/111387349-f7bb0a00-8683-11eb-899c-0701b8bce32c.png)

**Comment by jdtcn** [comment]
You should start Blazor.Server project intead of Blazor.Client

**Comment by jdtcn** [comment]
Have you solved this problem?
