### ISSUE TITLE
Browser history navigation broken

### ISSUE THREAD

**Issue by czorc** [jdtcn/HybridBlazor#7]
hi,
**thank you for your work** - the solution is very interesting.

However, I have the issue when navigating between pages and then using the browser back button to navigate to the previous page.
The URL is updated, but the page itself is not updated.

Would you have a solution or suggestion to fix this issue?

Many thanks in advance,
Christian

#### Environment:
- Tested with the last repo-version
- HybridType: HybridOnNavigation & HybridOnReady
- Used Browser
	- Google Chrome
	- Firefox 97.0.1 (64-Bit)

#### Test
- Debugging started (IIS Express)
- Navigated to Counter
- Navigated to Fetch
- Navigated to Home
- Browser history back button clicked
	- Result: URL changed to /fetchdata > the content remains unchanged

**Comment by jdtcn** [comment]
Hi!

Thank you for your interest and for the feedback. Indeed, there was a problem with the handling of `popstate` event, it turned out to be easy to fix: https://github.com/jdtcn/HybridBlazor/commit/21ff05709e3fa2ed2129cedf382d5ca280cc899e

Also updated the dependencies to the latest versions.

**Comment by czorc** [comment]
Hi,
thank you for the quick fix.
had been able to validate it positively the very next day.
Thx,
christian
